#!/usr/bin/env python3
"""Build deterministic SAM templates from the Kotlin conformance manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import yaml

MODULE = Path(__file__).resolve().parents[1]
MANIFEST = MODULE / "template-manifest.json"


class CloudFormationLoader(yaml.SafeLoader):
    pass


def _cloudformation_tag(
    loader: CloudFormationLoader,
    suffix: str,
    node: yaml.Node,
) -> dict[str, Any]:
    if isinstance(node, yaml.ScalarNode):
        value: Any = loader.construct_scalar(node)
    elif isinstance(node, yaml.SequenceNode):
        value = loader.construct_sequence(node, deep=True)
    else:
        value = loader.construct_mapping(node, deep=True)
    key = "Ref" if suffix == "Ref" else f"Fn::{suffix}"
    return {key: value}


CloudFormationLoader.add_multi_constructor("!", _cloudformation_tag)


def extract() -> None:
    suites: dict[str, Any] = {}
    for path in sorted(MODULE.glob("template_*.yaml")):
        suite = path.stem.removeprefix("template_")
        document = yaml.load(path.read_text(), Loader=CloudFormationLoader)
        function_globals = document.get("Globals", {}).get("Function", {})
        functions: list[dict[str, Any]] = []
        for logical_id, resource in document["Resources"].items():
            if resource.get("Type") != "AWS::Serverless::Function":
                continue
            properties = resource.get("Properties", {})
            entry: dict[str, Any] = {
                "id": logical_id,
                "handler": properties["Handler"],
                "description": properties.get("Description", logical_id),
            }
            if "TestingMetadata" in resource:
                entry["tests"] = resource["TestingMetadata"].get("TestDescription", [])
            if "DurableConfig" in properties:
                entry["durable"] = properties["DurableConfig"]
            for source, target in (
                ("Environment", "environment"),
                ("TenancyConfig", "tenancy"),
                ("Timeout", "timeout"),
            ):
                if source in properties:
                    entry[target] = properties[source]
            functions.append(entry)
        suites[suite] = {
            "logging": "LoggingConfig" in function_globals,
            "functions": functions,
        }
    MANIFEST.write_text(json.dumps({"suites": suites}, indent=2) + "\n")


def render_suite(name: str, suite: dict[str, Any]) -> str:
    globals_: dict[str, Any] = {
        "Function": {
            "Timeout": 60,
            "MemorySize": 512,
            "Runtime": {"Ref": "JavaVersion"},
            "Architectures": [{"Ref": "Architecture"}],
        },
    }
    if suite["logging"]:
        globals_["Function"]["LoggingConfig"] = {"LogFormat": "JSON"}

    resources: dict[str, Any] = {
        "DurableFunctionRole": execution_role(),
    }
    for function in suite["functions"]:
        properties: dict[str, Any] = {
            "CodeUri": "..",
            "Handler": function["handler"],
            "Description": function["description"],
            "Role": {"Fn::GetAtt": ["DurableFunctionRole", "Arn"]},
        }
        if "durable" in function:
            properties["DurableConfig"] = function["durable"]
        if "environment" in function:
            properties["Environment"] = function["environment"]
        if "tenancy" in function:
            properties["TenancyConfig"] = function["tenancy"]
        if "timeout" in function:
            properties["Timeout"] = function["timeout"]

        resource: dict[str, Any] = {
            "Type": "AWS::Serverless::Function",
            "Metadata": {"BuildMethod": "makefile"},
        }
        if "tests" in function:
            resource["TestingMetadata"] = {"TestDescription": function["tests"]}
        resource["Properties"] = properties
        resources[function["id"]] = resource

    document = {
        "AWSTemplateFormatVersion": "2010-09-09",
        "Transform": "AWS::Serverless-2016-10-31",
        "Description": f"Kotlin durable execution conformance: {name}",
        "Parameters": {
            "Architecture": {
                "Type": "String",
                "Default": "arm64",
                "AllowedValues": ["x86_64", "arm64"],
            },
            "JavaVersion": {
                "Type": "String",
                "Default": "java21",
            },
        },
        "Globals": globals_,
        "Resources": resources,
    }
    return "# Generated by scripts/templates.py. Edit template-manifest.json instead.\n" + yaml.safe_dump(
        document,
        sort_keys=False,
        width=1000,
    )


def execution_role() -> dict[str, Any]:
    return {
        "Type": "AWS::IAM::Role",
        "Properties": {
            "AssumeRolePolicyDocument": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": {"Service": "lambda.amazonaws.com"},
                        "Action": "sts:AssumeRole",
                    },
                ],
            },
            "ManagedPolicyArns": [
                "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
            ],
            "Policies": [
                {
                    "PolicyName": "DurableExecution",
                    "PolicyDocument": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Effect": "Allow",
                                "Action": [
                                    "lambda:CheckpointDurableExecution",
                                    "lambda:GetDurableExecutionState",
                                ],
                                "Resource": "*",
                            },
                        ],
                    },
                },
            ],
        },
    }


def generate(check: bool) -> None:
    manifest = json.loads(MANIFEST.read_text())
    mismatches: list[str] = []
    for name, suite in manifest["suites"].items():
        path = MODULE / f"template_{name}.yaml"
        rendered = render_suite(name, suite)
        if check:
            if not path.exists() or path.read_text() != rendered:
                mismatches.append(path.name)
        else:
            path.write_text(rendered)
    if mismatches:
        raise SystemExit("Templates are stale: " + ", ".join(mismatches))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("extract", "generate", "check"))
    args = parser.parse_args()
    if args.command == "extract":
        extract()
    else:
        generate(check=args.command == "check")


if __name__ == "__main__":
    main()
